version: '3.9'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.com
    restart: always

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:${DB_PASSWORD}@db:5432/fullfill
      - DEBUG=False
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ..
      dockerfile: docker/database/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fullfill
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: