version: '3.9'

services:
  frontend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: Fullfill_Docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/fullfill
      - DEBUG=True
    volumes:
      - ../backend:/app
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  db:
    build:
      context: ..
      dockerfile: Fullfill_Docker/database/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fullfill
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: