version: '3.9'

services:
  frontend:
    build:
      context: ..
      dockerfile: Fullfill_Docker/frontend/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.com
    restart: always

  backend:
    build:
      context: ..
      dockerfile: Fullfill_Docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://fullfill_user:${DB_PASSWORD}@db:5432/fullfill
      - DEBUG=False
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ..
      dockerfile: Fullfill_Docker/database/Dockerfile
    environment:
      - POSTGRES_USER=fullfill_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fullfill
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fullfill_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: